### ISSUE TITLE
Export as table error

### ISSUE THREAD

**Issue by jpburelle** [FacilMap/facilmap#153]
When exporting my facilmap as Table I get the following error page:

TypeError: ejs:54
    52| 			for(let field of type.fields) {
    53| 				if(!hide.includes(field.name)) {
 >> 54| -%> <td><%-utils.formatField(field, object.data[field.name]).trim()%></td> <%
    55| 				}
    56| 			}
    57| -%> </tr> <%

dom_1.$ is not a function
    at applyMarkdownModifications (/opt/facilmap/utils/dist/format.js:61:11)
    at markdownBlock (/opt/facilmap/utils/dist/format.js:35:5)
    at Object.formatField (/opt/facilmap/utils/dist/format.js:21:20)
    at eval (eval at compile (/opt/facilmap/node_modules/ejs/lib/ejs.js:662:12), <anonymous>:142:22)
    at anonymous (/opt/facilmap/node_modules/ejs/lib/ejs.js:692:17)
    at Object.exports.render (/opt/facilmap/node_modules/ejs/lib/ejs.js:423:37)
    at /opt/facilmap/server/dist/export/table.js:65:30
    at async /opt/facilmap/server/dist/webserver.js:93:35

**Comment by cdauth** [comment]
Thanks for reporting! This should be fixed now.
